version: "3.7"

volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: gainutdinov/vote:master
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - instavote
  
  redis:
    image: redis:alpine
    networks:
      - instavote
  
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - instavote
  
  result:
    image: gainutdinov/result:master
    ports:
    - 5001:4000
    depends_on:
      - db
    networks:
      - instavote
  
  worker:
    image: gainutdinov/worker:master
    depends_on:
      - redis
      - db
    networks:
      - instavote
